version: '3'

services:
  web:
    image: ipushc/yapi:latest
    environment:
      TZ: Asia/Taipei
    volumes:
      - .:/yapi
    ports:
      - 8083:9090
      - 8084:3000
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: yapi_mongodb
    volumes:
      - ./mongo/db:/data/db